### ISSUE TITLE
getting a error

### ISSUE THREAD

**Issue by Samvandop** [VangelisBV/vanmoof-battery-tool#3]
\\          //
 \\        //
  \\      //
   \\    //
    \\  //
     \\//
VB Tool v1.0.1

Available serial ports:
0: /dev/cu.Bluetooth-Incoming-Port - n/a
1: /dev/cu.usbserial-0001 - CP2102 USB to UART Bridge Controller
2: /dev/cu.SLAB_USBtoUART - CP2102 USB to UART Bridge Controller

Enter the index number of the port you want to connect to: 2
Connected to /dev/cu.SLAB_USBtoUART.
 
Bridge the DET and TEST pins
I am G5 VanMoof BL V004 2019-11-19

Serial exception error: ModbusSerialClient.__init__() got an unexpected keyword argument 'method'

this is the error i got

**Comment by Samvandop** [comment]
fixed it!

removed:

method="rtu"

because pymodbus from 3.7.0 is default method ("rtu") so no need to give that argument

**Comment by VangelisBV** [comment]
Thanks for the feedback.
I deleted the method and added specific versions for the libraries in requirements.
