### ISSUE TITLE
Reset error register

### ISSUE THREAD

**Issue by tueddy** [VangelisBV/vanmoof-battery-tool#5]
First thanks for this great tool! Not an issue, more a question:

I've replaced the fuse and can read the battery registers now:

`
I am VanMoof BL V007 2022-11-xx xx:xx:xx

Errors: Charging Over Current Protection 2,Charging Over Current Protection 1
Voltage: 40.505 Volt
SOC: 86 %
ESN: D3A02209I0xxxx
Nominal Capacity: 12600 mAh
Full Charge Capacity: 12578 mAh
Remaining Capacity: 10722 mAh
Cycles: 40
Cells Pack 1: 4.054 V
Cells Pack 2: 4.053 V
Cells Pack 3: 4.052 V
Cells Pack 4: 4.051 V
Cells Pack 5: 4.05 V
Cells Pack 6: 4.051 V
Cells Pack 7: 4.05 V
Cells Pack 8: 4.048 V
Cells Pack 9: 4.048 V
Cells Pack 10: 4.048 V
Cell Packs Max Actual: 4.054 V
Cell Packs Min Actual: 4.048 V
`
Now i want to reset the error register. 
I found a way but it's a bit complicated and i would need a SWD programmer:
https://www.reddit.com/r/VanMoofSelfRepair/comments/1gtkka6/reset_over_voltage_protection_1_2/

Would it be possible also to write the error register with your tool?

**Comment by VangelisBV** [comment]
Hello, I don't think is possible. 
I would also recommend you to buy a programmer. 
You can find them for very low price (fe ST Link V2 mini).

Else you can try something like this:
https://www.reddit.com/r/VanMoofSelfRepair/comments/1gsxit1/comment/ly2g8le/?share_id=uwlOIonehTaX9-O9L768O&utm_content=2&utm_medium=android_app&utm_name=androidcss&utm_source=share&utm_term=1

**Comment by tueddy** [comment]
Hi @VangelisBV ,
thank's for your answer! In the meantime i managed to reset the error register, the battery is fully functional now!

![grafik](https://github.com/user-attachments/assets/9d3dc648-ae27-42b9-adbf-d0f25fb65b08)
